apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
  namespace: argocd-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/noname-artifacts/nns-docker/nginx@sha256:06233d0d575146461dd91080d3b31382de01f0e92150cbd442cfba7b0dda7a6a
        name: nginx
